# Generated by Django 4.1.2 on 2022-10-22 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supers_types', '0001_initial'),
        ('supers', '0002_super_supers_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='super',
            name='supers_types',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='supers_types.superstypes'),
            preserve_default=False,
        ),
    ]
